'use strict';
// Rynek Shop EXTREME-LITE — Node.js 18, 0 paczek npm, tylko moduły wbudowane.
const https=require('https'),tls=require('tls'),crypto=require('crypto'),fs=require('fs'),path=require('path');

// .env (opcjonalny; ACLClouds może używać Environment Variables)
try{for(const l of fs.readFileSync(path.join(__dirname,'.env'),'utf8').split(/\r?\n/)){if(!l||l[0]==='#')continue;const i=l.indexOf('=');if(i>0&&!process.env[l.slice(0,i)])process.env[l.slice(0,i)]=l.slice(i+1).trim();}}catch{}
const TOKEN=process.env.DISCORD_TOKEN,GUILD=process.env.GUILD_ID;
if(!TOKEN||!GUILD){console.error('Brak DISCORD_TOKEN lub GUILD_ID');process.exit(1)}

const BRAND='Rynek Shop',COLOR=0x3498DB,CAT='1499321421979975833',STAFF='1499321419648077883',LEGIT='1506203473778049096';
const PRODUCTS={Jailbreak:'1506203233633304688',Robux:'1512697980011151432',MM2:'1546969811798462474','case-world':'1548648793095020574',Petsim99:'1506203270757089322'};
const ASSET={ticket:'ticket-banner.jpg',legit:'legit-banner.jpg',products:'products-banner.png'};
const tickets=new Map(),emojis=new Map(); let BOT='',SEQ=null,HB=null,sock=null,buf=Buffer.alloc(0),frag='';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const j=x=>JSON.stringify(x), row=(...c)=>({type:1,components:c}), btn=(id,label,style=1,e)=>({type:2,custom_id:id,label,style,...(e?{emoji:emoji(e)}:{})});
function ce(n,f){const e=emojis.get(n);return e?`<${e.animated?'a':''}:${e.name}:${e.id}>`:f}
function emoji(n){const e=emojis.get(n);return e?{id:e.id,name:e.name,animated:e.animated}:undefined}
function staff(m){return !!m&&(((BigInt(m.permissions||'0')&8n)===8n)||(m.roles||[]).includes(STAFF))}
function footer(t){return {text:`© 2026 ${BRAND} × ${t}`}}
function val(i,id){for(const r of i.data?.components||[])for(const c of r.components||[])if(c.custom_id===id)return String(c.value||'');return ''}
function clean(s){return String(s||'user').toLowerCase().replace(/[^a-z0-9-_]/g,'-').replace(/-+/g,'-').slice(0,28)||'user'}

// REST przez wbudowane https — bez fetch/undici.
function req(method,route,body,extra={}){return new Promise((resolve,reject)=>{let data=body==null?null:Buffer.from(typeof body==='string'?body:j(body));const q=https.request({hostname:'discord.com',path:'/api/v10'+route,method,headers:{Authorization:'Bot '+TOKEN,...(data?{'Content-Type':'application/json','Content-Length':data.length}:{}),...extra}},r=>{const a=[];r.on('data',x=>a.push(x));r.on('end',async()=>{const s=Buffer.concat(a).toString();if(r.statusCode===429){let t=1000;try{t=Math.ceil(JSON.parse(s).retry_after*1000)}catch{};await sleep(t+50);return req(method,route,body,extra).then(resolve,reject)}if(r.statusCode>=400)return reject(Error(`Discord ${r.statusCode}: ${s.slice(0,250)}`));if(!s)return resolve(null);try{resolve(JSON.parse(s))}catch{resolve(s)}})});q.on('error',reject);if(data)q.end(data);else q.end()})}
function upload(channel,payload,file){return new Promise((resolve,reject)=>{const boundary='----rs'+Date.now().toString(36),fileBuf=fs.readFileSync(path.join(__dirname,file)),p={...payload,attachments:[{id:0,filename:file}]};const head=Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="payload_json"\r\nContent-Type: application/json\r\n\r\n${j(p)}\r\n--${boundary}\r\nContent-Disposition: form-data; name="files[0]"; filename="${file}"\r\nContent-Type: image/${file.endsWith('.png')?'png':'jpeg'}\r\n\r\n`),tail=Buffer.from(`\r\n--${boundary}--\r\n`),len=head.length+fileBuf.length+tail.length;const q=https.request({hostname:'discord.com',path:`/api/v10/channels/${channel}/messages`,method:'POST',headers:{Authorization:'Bot '+TOKEN,'Content-Type':'multipart/form-data; boundary='+boundary,'Content-Length':len}},r=>{const a=[];r.on('data',x=>a.push(x));r.on('end',()=>{const s=Buffer.concat(a).toString();if(r.statusCode>=400)return reject(Error(`Upload ${r.statusCode}: ${s.slice(0,250)}`));try{resolve(JSON.parse(s))}catch{resolve(null)}})});q.on('error',reject);q.write(head);q.write(fileBuf);q.end(tail)})}
const cb=(i,type,data)=>req('POST',`/interactions/${i.id}/${i.token}/callback`,data===undefined?{type}:{type,data});
const eph=(i,content)=>cb(i,4,{content,flags:64});

function panelTicket(){return {embeds:[{color:COLOR,title:'🌊  ·  RYNEK SHOP × TICKETY',description:`${ce('71334shop','🛒')}  ·  **Chcesz zakupić przedmiot lub potrzebujesz pomocy?**\n${ce('259419darkbluearrow','»')}  ·  Kliknij przycisk i wypełnij formularz.`,image:{url:'attachment://ticket-banner.jpg'},footer:footer('Panel Ticketów')}],components:[row(btn('t:new','Stwórz ticket',1,'71334shop'))]}}
function panelProducts(){return {embeds:[{color:COLOR,title:'🌊  ·  RYNEK SHOP × PRODUKTY',description:`${ce('71334shop','🛒')}  ·  Wybierz kategorię, a pokażemy kanał z cenami.`,image:{url:'attachment://products-banner.png'},footer:footer('Produkty')}],components:[row({type:3,custom_id:'p:pick',placeholder:'Wybierz kategorię',options:Object.keys(PRODUCTS).map(x=>({label:x,value:x}))})]}}
function panelLegit(){return {embeds:[{color:COLOR,title:'🌊  ·  RYNEK SHOP × LEGIT CHECK',description:`${ce('71334shop','🛒')}  ·  **Wzór:**\n\`+rep @Użytkownik (co zakupiłeś/sprzedałeś) (metoda płatności)\`\n\n**Przykład:**\n\`+rep @auto_wywrotka torpedo (blik)\``,image:{url:'attachment://legit-banner.jpg'},footer:footer('Legit Check')}]}}
function modal(){const f=(id,l,p)=>({type:4,custom_id:id,label:l,style:1,required:true,max_length:100,placeholder:p});return {custom_id:'t:modal',title:'Formularz Zakupu',components:[row(f('item','Co chcesz zakupić?','np. Robux / item')),row(f('amount','Kwota','np. 50 PLN')),row(f('pay','Metoda płatności','np. BLIK / PSC'))]}}
function ticketEmbed(u,t){return {embeds:[{color:COLOR,title:'🌊  ·  RYNEK SHOP × ZAKUP',description:`${ce('71334shop','🛒')} **Informacje o tickecie**\n• Klient: <@${u.id}>\n• ID: \`${t.id}\`\n• Co kupuje: **${t.item}**\n• Kwota: **${t.amount}**\n• Płatność: **${t.pay}**\n• Przejął: ${t.claim?`<@${t.claim}>`:'Nikt'}`,footer:footer('Zakup')}],components:[row(btn('t:close','Zamknij',4,'31274xids'),btn('t:claim','Przejmij',1,'weryfikacja_1'),btn('t:set','Ustawienia',2,'bot'))]}}

async function commands(){await req('PUT',`/applications/${BOT}/guilds/${GUILD}/commands`,[{name:'panel-ticket',description:'Wyślij panel ticketów'},{name:'panel-produkty',description:'Wyślij panel produktów'},{name:'sticky-legit',description:'Wyślij Legit Check'}])}
async function onInteraction(i){try{const u=i.member?.user||i.user||{};if(i.type===2){if(!staff(i.member))return eph(i,'❌ Tylko administracja/sprzedawca.');if(i.data.name==='panel-ticket'){await upload(i.channel_id,panelTicket(),ASSET.ticket);return eph(i,'✅ Panel ticketów wysłany.')}if(i.data.name==='panel-produkty'){await upload(i.channel_id,panelProducts(),ASSET.products);return eph(i,'✅ Panel produktów wysłany.')}if(i.data.name==='sticky-legit'){await upload(i.channel_id,panelLegit(),ASSET.legit);return eph(i,'✅ Legit Check wysłany.')}}
if(i.type===3){const id=i.data.custom_id;if(id==='t:new')return cb(i,9,modal());if(id==='p:pick'){const x=i.data.values?.[0],ch=PRODUCTS[x];return eph(i,`🌊 **${x}**\n${ce('71334shop','🛒')} Ceny znajdziesz na kanale <#${ch}>.`)}const t=tickets.get(i.channel_id);if(!t)return eph(i,'Ticket nie jest już aktywny.');if(!staff(i.member))return eph(i,'❌ Te przyciski są tylko dla administracji/sprzedawcy.');if(id==='t:claim'){t.claim=u.id;await cb(i,7,ticketEmbed({id:t.owner},t));return}if(id==='t:set')return eph(i,'⚙️ Ustawienia ticketu są dostępne dla staffu.');if(id==='t:close'){await cb(i,6);try{const dm=await req('POST','/users/@me/channels',{recipient_id:t.owner});await req('POST',`/channels/${dm.id}/messages`,{embeds:[{color:COLOR,title:'🌊  ·  RYNEK SHOP × ZAMKNIĘTO TICKET',description:`Twój ticket został **zamknięty**.\n\n${ce('71334shop','🛒')} **Informacje:**\n• ID: \`${t.id}\`\n• Przedmiot: **${t.item}**\n• Kwota: **${t.amount}**\n• Płatność: **${t.pay}**\n• Zamknął: <@${u.id}>`,footer:footer('Zamknięto ticket')}]})}catch{}tickets.delete(i.channel_id);setTimeout(()=>req('DELETE',`/channels/${i.channel_id}`).catch(()=>{}),1000);return}}
if(i.type===5&&i.data.custom_id==='t:modal'){await cb(i,5,{flags:64});const t={id:crypto.randomBytes(4).toString('hex'),owner:u.id,item:val(i,'item'),amount:val(i,'amount'),pay:val(i,'pay'),claim:null};const ch=await req('POST',`/guilds/${GUILD}/channels`,{name:`ticket-${clean(u.username)}`,type:0,parent_id:CAT,permission_overwrites:[{id:GUILD,type:0,deny:'1024'},{id:u.id,type:1,allow:'68608'},{id:STAFF,type:0,allow:'68608'}]});tickets.set(ch.id,t);await req('POST',`/channels/${ch.id}/messages`,ticketEmbed(u,t));await req('PATCH',`/webhooks/${i.application_id}/${i.token}/messages/@original`,{content:`✅ Ticket utworzony: <#${ch.id}>`});}}
catch(e){console.error('interaction:',e.message);try{await eph(i,'❌ Wystąpił błąd.')}catch{}}}

// Minimalny WebSocket RFC6455 do Discord Gateway.
function frame(s){const p=Buffer.from(s),n=p.length,m=crypto.randomBytes(4);let h;if(n<126){h=Buffer.from([0x81,0x80|n])}else{h=Buffer.alloc(4);h[0]=0x81;h[1]=0xfe;h.writeUInt16BE(n,2)}const x=Buffer.alloc(n);for(let i=0;i<n;i++)x[i]=p[i]^m[i&3];return Buffer.concat([h,m,x])}
function sendGW(o){if(sock&&!sock.destroyed)sock.write(frame(j(o)))}
function parse(){while(buf.length>=2){let b0=buf[0],b1=buf[1],op=b0&15,fin=!!(b0&128),n=b1&127,p=2;if(n===126){if(buf.length<4)return;n=buf.readUInt16BE(2);p=4}else if(n===127){if(buf.length<10)return;n=Number(buf.readBigUInt64BE(2));p=10}if(buf.length<p+n)return;const d=buf.subarray(p,p+n);buf=buf.subarray(p+n);if(op===8){return reconnect()}if(op===9){sock.write(Buffer.concat([Buffer.from([0x8a,d.length]),d]));continue}if(op===1){frag=d.toString();if(fin)handle(frag)}else if(op===0){frag+=d.toString();if(fin)handle(frag)}}}
function handle(s){let x;try{x=JSON.parse(s)}catch{return}if(x.s!=null)SEQ=x.s;if(x.op===10){clearInterval(HB);HB=setInterval(()=>sendGW({op:1,d:SEQ}),x.d.heartbeat_interval);sendGW({op:2,d:{token:TOKEN,intents:1,properties:{os:'linux',browser:'rynek',device:'rynek'}}});return}if(x.op===7)return reconnect();if(x.t==='READY'){BOT=x.d.user.id;req('GET',`/guilds/${GUILD}/emojis`).then(a=>{for(const e of a||[])emojis.set(e.name,e)}).catch(()=>{});commands().then(()=>console.log('Rynek Shop online. RAM-minimal mode.')).catch(e=>console.error(e.message));return}if(x.t==='INTERACTION_CREATE')onInteraction(x.d)}
function reconnect(){clearInterval(HB);try{sock?.destroy()}catch{};setTimeout(connect,3000)}
function connect(){const key=crypto.randomBytes(16).toString('base64');sock=tls.connect(443,'gateway.discord.gg',{servername:'gateway.discord.gg'});let hs=true;buf=Buffer.alloc(0);sock.on('secureConnect',()=>sock.write(`GET /?v=10&encoding=json HTTP/1.1\r\nHost: gateway.discord.gg\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: ${key}\r\nSec-WebSocket-Version: 13\r\n\r\n`));sock.on('data',d=>{if(hs){const s=d.toString('latin1'),i=s.indexOf('\r\n\r\n');if(i<0)return;if(!s.startsWith('HTTP/1.1 101'))return reconnect();hs=false;const rest=d.subarray(i+4);if(rest.length){buf=Buffer.concat([buf,rest]);parse()}return}buf=Buffer.concat([buf,d]);parse()});sock.on('error',()=>reconnect());sock.on('close',()=>reconnect())}
connect();
